[package]
name = "fc-traits-authn-proc"
version.workspace = true
authors.workspace = true
description = "Procedural macros supporting fc-traits-authn."
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro-crate.workspace = true