// This file is part of FRAME Contrib.

// Copyright (C) Virto Network.
// SPDX-License-Identifier: GPL-3.0-only

//! Autogenerated weights for `fc_pallet_listings`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 60.0.0
//! DATE: 2026-10-02, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `virto-bench-soegbx1mb2x8`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=/home/runner/actions-runner/_work/_temp/runtime/fc_kitchensink_runtime.compact.compressed.wasm
// --pallet=fc_pallet_listings
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template=/home/runner/actions-runner/_work/frame-contrib/frame-contrib/pr/.maintain/frame-weight-template.hbs
// --header=/home/runner/actions-runner/_work/frame-contrib/frame-contrib/pr/.maintain/file_header.txt
// --output=pallets/listings/src/weights.rs
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `fc_pallet_listings`.
pub trait WeightInfo {
	fn create_inventory() -> Weight;
	fn archive_inventory() -> Weight;
	fn publish_item(q: u32, ) -> Weight;
	fn mark_item_can_transfer() -> Weight;
	fn mark_item_not_for_resale() -> Weight;
	fn set_item_price() -> Weight;
	fn clear_item_price() -> Weight;
	fn set_item_attribute(p: u32, q: u32, ) -> Weight;
	fn clear_item_attribute(p: u32, q: u32, ) -> Weight;
	fn set_subscription_conditions() -> Weight;
	fn subscribe() -> Weight;
	fn charge_due() -> Weight;
	fn cancel_subscription() -> Weight;
	fn terminate_subscription() -> Weight;
	fn schedule_replacement() -> Weight;
	fn amend_subscription() -> Weight;
	fn cancel_replacement() -> Weight;
	fn amend_item_subscriptions() -> Weight;
	fn process_due(n: u32, ) -> Weight;
	fn process_due_replacement() -> Weight;
	fn skip_empty_bucket() -> Weight;
	fn process_due_overflow() -> Weight;
	fn settle_subscription() -> Weight;
}

/// Weights for `fc_pallet_listings`, generated with the FRAME Contrib kitchensink runtime on reference hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionRoleOf` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionRoleOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionConfigOf` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionAccount` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionAccount` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn create_inventory() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `182`
		//  Estimated: `3593`
		// Minimum execution time: 26_688_000 picoseconds.
		Weight::from_parts(28_038_000, 3593)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:1 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	fn archive_inventory() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `258`
		//  Estimated: `3948`
		// Minimum execution time: 23_353_000 picoseconds.
		Weight::from_parts(24_764_000, 3948)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:2)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:1)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionConfigOf` (r:1 w:0)
	/// Proof: `ListingsCatalog::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::ItemConfigOf` (r:1 w:1)
	/// Proof: `ListingsCatalog::ItemConfigOf` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Account` (r:0 w:1)
	/// Proof: `ListingsCatalog::Account` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// The range of component `q` is `[1, 230]`.
	fn publish_item(q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `493`
		//  Estimated: `9864`
		// Minimum execution time: 68_115_000 picoseconds.
		Weight::from_parts(70_644_895, 9864)
			// Standard Error: 72
			.saturating_add(Weight::from_parts(1_886, 0).saturating_mul(q.into()))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:2 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	fn mark_item_can_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `559`
		//  Estimated: `6906`
		// Minimum execution time: 31_283_000 picoseconds.
		Weight::from_parts(32_786_000, 6906)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	fn mark_item_not_for_resale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `568`
		//  Estimated: `9864`
		// Minimum execution time: 35_419_000 picoseconds.
		Weight::from_parts(36_911_000, 9864)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:2 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	fn set_item_price() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `568`
		//  Estimated: `6906`
		// Minimum execution time: 39_945_000 picoseconds.
		Weight::from_parts(41_488_000, 6906)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:2 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	fn clear_item_price() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `590`
		//  Estimated: `6906`
		// Minimum execution time: 39_475_000 picoseconds.
		Weight::from_parts(41_538_000, 6906)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 59]`.
	/// The range of component `q` is `[1, 251]`.
	fn set_item_attribute(p: u32, q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `568`
		//  Estimated: `9864`
		// Minimum execution time: 34_518_000 picoseconds.
		Weight::from_parts(35_436_797, 9864)
			// Standard Error: 116
			.saturating_add(Weight::from_parts(9_823, 0).saturating_mul(p.into()))
			// Standard Error: 27
			.saturating_add(Weight::from_parts(1_401, 0).saturating_mul(q.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 59]`.
	/// The range of component `q` is `[1, 251]`.
	fn clear_item_attribute(p: u32, q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `614 + p * (1 ±0) + q * (1 ±0)`
		//  Estimated: `9864`
		// Minimum execution time: 31_233_000 picoseconds.
		Weight::from_parts(32_052_097, 9864)
			// Standard Error: 108
			.saturating_add(Weight::from_parts(15_717, 0).saturating_mul(p.into()))
			// Standard Error: 25
			.saturating_add(Weight::from_parts(920, 0).saturating_mul(q.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:0)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:2 w:0)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemConditions` (r:1 w:1)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	fn set_subscription_conditions() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `988`
		//  Estimated: `6906`
		// Minimum execution time: 40_115_000 picoseconds.
		Weight::from_parts(41_978_000, 6906)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:0)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:1 w:0)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemConditions` (r:1 w:0)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:2 w:0)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:2 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Payment` (r:1 w:0)
	/// Proof: `Orders::Payment` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:1)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueQueue` (r:1 w:1)
	/// Proof: `Listings::DueQueue` (`max_values`: None, `max_size`: Some(2830), added: 5305, mode: `MaxEncodedLen`)
	fn subscribe() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1302`
		//  Estimated: `8817`
		// Minimum execution time: 155_835_000 picoseconds.
		Weight::from_parts(164_057_000, 8817)
			.saturating_add(T::DbWeight::get().reads(19_u64))
			.saturating_add(T::DbWeight::get().writes(10_u64))
	}
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Collection` (r:1 w:0)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:2 w:0)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:2 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Payment` (r:1 w:0)
	/// Proof: `Orders::Payment` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn charge_due() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1260`
		//  Estimated: `8817`
		// Minimum execution time: 143_790_000 picoseconds.
		Weight::from_parts(149_157_000, 8817)
			.saturating_add(T::DbWeight::get().reads(14_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn cancel_subscription() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `287`
		//  Estimated: `3676`
		// Minimum execution time: 21_521_000 picoseconds.
		Weight::from_parts(22_742_000, 3676)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueQueue` (r:1 w:1)
	/// Proof: `Listings::DueQueue` (`max_values`: None, `max_size`: Some(2830), added: 5305, mode: `MaxEncodedLen`)
	fn terminate_subscription() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `325`
		//  Estimated: `6295`
		// Minimum execution time: 16_283_000 picoseconds.
		Weight::from_parts(17_214_000, 6295)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Listings::Subscriptions` (r:2 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemConditions` (r:1 w:0)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn schedule_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `369`
		//  Estimated: `6362`
		// Minimum execution time: 26_838_000 picoseconds.
		Weight::from_parts(28_209_000, 6362)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn amend_subscription() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `631`
		//  Estimated: `3676`
		// Minimum execution time: 25_985_000 picoseconds.
		Weight::from_parts(27_287_000, 3676)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn cancel_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3676`
		// Minimum execution time: 17_685_000 picoseconds.
		Weight::from_parts(18_627_000, 3676)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Listings::ItemConditions` (r:1 w:1)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:1)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	fn amend_item_subscriptions() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `501`
		//  Estimated: `3675`
		// Minimum execution time: 17_364_000 picoseconds.
		Weight::from_parts(18_365_000, 3675)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Listings::DueQueue` (r:2 w:2)
	/// Proof: `Listings::DueQueue` (`max_values`: None, `max_size`: Some(2830), added: 5305, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:64 w:64)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Collection` (r:1 w:0)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:66 w:66)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:65 w:0)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:65 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Payment` (r:64 w:0)
	/// Proof: `Orders::Payment` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueOverflow` (r:1 w:0)
	/// Proof: `Listings::DueOverflow` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 64]`.
	fn process_due(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1132 + n * (237 ±0)`
		//  Estimated: `11600 + n * (2686 ±0)`
		// Minimum execution time: 151_641_000 picoseconds.
		Weight::from_parts(27_461_482, 11600)
			// Standard Error: 93_540
			.saturating_add(Weight::from_parts(126_185_815, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().reads((5_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(6_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2686).saturating_mul(n.into()))
	}
	/// Storage: `Listings::DueQueue` (r:2 w:2)
	/// Proof: `Listings::DueQueue` (`max_values`: None, `max_size`: Some(2830), added: 5305, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:2 w:2)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:2 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemConditions` (r:1 w:0)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:1 w:0)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Collection` (r:1 w:0)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:2 w:0)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:2 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Payment` (r:1 w:0)
	/// Proof: `Orders::Payment` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueOverflow` (r:1 w:0)
	/// Proof: `Listings::DueOverflow` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn process_due_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1480`
		//  Estimated: `11600`
		// Minimum execution time: 169_305_000 picoseconds.
		Weight::from_parts(176_846_000, 11600)
			.saturating_add(T::DbWeight::get().reads(20_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
	/// Storage: `Listings::DueQueue` (r:1 w:0)
	/// Proof: `Listings::DueQueue` (`max_values`: None, `max_size`: Some(2830), added: 5305, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueOverflow` (r:1 w:0)
	/// Proof: `Listings::DueOverflow` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn skip_empty_bucket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `6295`
		// Minimum execution time: 5_097_000 picoseconds.
		Weight::from_parts(5_498_000, 6295)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	/// Storage: `Listings::DueQueue` (r:4 w:3)
	/// Proof: `Listings::DueQueue` (`max_values`: None, `max_size`: Some(2830), added: 5305, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueOverflow` (r:2 w:2)
	/// Proof: `Listings::DueOverflow` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Collection` (r:1 w:0)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:2 w:0)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:2 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Payment` (r:1 w:0)
	/// Proof: `Orders::Payment` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn process_due_overflow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9857`
		//  Estimated: `22210`
		// Minimum execution time: 165_399_000 picoseconds.
		Weight::from_parts(172_709_000, 22210)
			.saturating_add(T::DbWeight::get().reads(19_u64))
			.saturating_add(T::DbWeight::get().writes(11_u64))
	}
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Listings::PausedTicks` (r:1 w:0)
	/// Proof: `Listings::PausedTicks` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Listings::LastPause` (r:1 w:0)
	/// Proof: `Listings::LastPause` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Listings::PauseStartedAt` (r:1 w:0)
	/// Proof: `Listings::PauseStartedAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn settle_subscription() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `346`
		//  Estimated: `3676`
		// Minimum execution time: 20_078_000 picoseconds.
		Weight::from_parts(21_379_000, 3676)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionRoleOf` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionRoleOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionConfigOf` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionAccount` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionAccount` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn create_inventory() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `182`
		//  Estimated: `3593`
		// Minimum execution time: 26_688_000 picoseconds.
		Weight::from_parts(28_038_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:1 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	fn archive_inventory() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `258`
		//  Estimated: `3948`
		// Minimum execution time: 23_353_000 picoseconds.
		Weight::from_parts(24_764_000, 3948)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:2)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:1)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionConfigOf` (r:1 w:0)
	/// Proof: `ListingsCatalog::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::ItemConfigOf` (r:1 w:1)
	/// Proof: `ListingsCatalog::ItemConfigOf` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Account` (r:0 w:1)
	/// Proof: `ListingsCatalog::Account` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// The range of component `q` is `[1, 230]`.
	fn publish_item(q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `493`
		//  Estimated: `9864`
		// Minimum execution time: 68_115_000 picoseconds.
		Weight::from_parts(70_644_895, 9864)
			// Standard Error: 72
			.saturating_add(Weight::from_parts(1_886, 0).saturating_mul(q.into()))
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:2 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	fn mark_item_can_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `559`
		//  Estimated: `6906`
		// Minimum execution time: 31_283_000 picoseconds.
		Weight::from_parts(32_786_000, 6906)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	fn mark_item_not_for_resale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `568`
		//  Estimated: `9864`
		// Minimum execution time: 35_419_000 picoseconds.
		Weight::from_parts(36_911_000, 9864)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:2 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	fn set_item_price() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `568`
		//  Estimated: `6906`
		// Minimum execution time: 39_945_000 picoseconds.
		Weight::from_parts(41_488_000, 6906)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:2 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	fn clear_item_price() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `590`
		//  Estimated: `6906`
		// Minimum execution time: 39_475_000 picoseconds.
		Weight::from_parts(41_538_000, 6906)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 59]`.
	/// The range of component `q` is `[1, 251]`.
	fn set_item_attribute(p: u32, q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `568`
		//  Estimated: `9864`
		// Minimum execution time: 34_518_000 picoseconds.
		Weight::from_parts(35_436_797, 9864)
			// Standard Error: 116
			.saturating_add(Weight::from_parts(9_823, 0).saturating_mul(p.into()))
			// Standard Error: 27
			.saturating_add(Weight::from_parts(1_401, 0).saturating_mul(q.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 59]`.
	/// The range of component `q` is `[1, 251]`.
	fn clear_item_attribute(p: u32, q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `614 + p * (1 ±0) + q * (1 ±0)`
		//  Estimated: `9864`
		// Minimum execution time: 31_233_000 picoseconds.
		Weight::from_parts(32_052_097, 9864)
			// Standard Error: 108
			.saturating_add(Weight::from_parts(15_717, 0).saturating_mul(p.into()))
			// Standard Error: 25
			.saturating_add(Weight::from_parts(920, 0).saturating_mul(q.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:0)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:2 w:0)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemConditions` (r:1 w:1)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	fn set_subscription_conditions() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `988`
		//  Estimated: `6906`
		// Minimum execution time: 40_115_000 picoseconds.
		Weight::from_parts(41_978_000, 6906)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:0)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:1 w:0)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemConditions` (r:1 w:0)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:2 w:0)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:2 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Payment` (r:1 w:0)
	/// Proof: `Orders::Payment` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:1)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueQueue` (r:1 w:1)
	/// Proof: `Listings::DueQueue` (`max_values`: None, `max_size`: Some(2830), added: 5305, mode: `MaxEncodedLen`)
	fn subscribe() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1302`
		//  Estimated: `8817`
		// Minimum execution time: 155_835_000 picoseconds.
		Weight::from_parts(164_057_000, 8817)
			.saturating_add(RocksDbWeight::get().reads(19_u64))
			.saturating_add(RocksDbWeight::get().writes(10_u64))
	}
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Collection` (r:1 w:0)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:2 w:0)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:2 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Payment` (r:1 w:0)
	/// Proof: `Orders::Payment` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn charge_due() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1260`
		//  Estimated: `8817`
		// Minimum execution time: 143_790_000 picoseconds.
		Weight::from_parts(149_157_000, 8817)
			.saturating_add(RocksDbWeight::get().reads(14_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn cancel_subscription() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `287`
		//  Estimated: `3676`
		// Minimum execution time: 21_521_000 picoseconds.
		Weight::from_parts(22_742_000, 3676)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueQueue` (r:1 w:1)
	/// Proof: `Listings::DueQueue` (`max_values`: None, `max_size`: Some(2830), added: 5305, mode: `MaxEncodedLen`)
	fn terminate_subscription() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `325`
		//  Estimated: `6295`
		// Minimum execution time: 16_283_000 picoseconds.
		Weight::from_parts(17_214_000, 6295)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Listings::Subscriptions` (r:2 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemConditions` (r:1 w:0)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn schedule_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `369`
		//  Estimated: `6362`
		// Minimum execution time: 26_838_000 picoseconds.
		Weight::from_parts(28_209_000, 6362)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn amend_subscription() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `631`
		//  Estimated: `3676`
		// Minimum execution time: 25_985_000 picoseconds.
		Weight::from_parts(27_287_000, 3676)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn cancel_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3676`
		// Minimum execution time: 17_685_000 picoseconds.
		Weight::from_parts(18_627_000, 3676)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Listings::ItemConditions` (r:1 w:1)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:1)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	fn amend_item_subscriptions() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `501`
		//  Estimated: `3675`
		// Minimum execution time: 17_364_000 picoseconds.
		Weight::from_parts(18_365_000, 3675)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Listings::DueQueue` (r:2 w:2)
	/// Proof: `Listings::DueQueue` (`max_values`: None, `max_size`: Some(2830), added: 5305, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:64 w:64)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Collection` (r:1 w:0)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:66 w:66)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:65 w:0)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:65 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Payment` (r:64 w:0)
	/// Proof: `Orders::Payment` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueOverflow` (r:1 w:0)
	/// Proof: `Listings::DueOverflow` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 64]`.
	fn process_due(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1132 + n * (237 ±0)`
		//  Estimated: `11600 + n * (2686 ±0)`
		// Minimum execution time: 151_641_000 picoseconds.
		Weight::from_parts(27_461_482, 11600)
			// Standard Error: 93_540
			.saturating_add(Weight::from_parts(126_185_815, 0).saturating_mul(n.into()))
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().reads((5_u64).saturating_mul(n.into())))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
			.saturating_add(RocksDbWeight::get().writes((2_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 2686).saturating_mul(n.into()))
	}
	/// Storage: `Listings::DueQueue` (r:2 w:2)
	/// Proof: `Listings::DueQueue` (`max_values`: None, `max_size`: Some(2830), added: 5305, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:2 w:2)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:2 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemConditions` (r:1 w:0)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:1 w:0)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Collection` (r:1 w:0)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:2 w:0)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:2 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Payment` (r:1 w:0)
	/// Proof: `Orders::Payment` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueOverflow` (r:1 w:0)
	/// Proof: `Listings::DueOverflow` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn process_due_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1480`
		//  Estimated: `11600`
		// Minimum execution time: 169_305_000 picoseconds.
		Weight::from_parts(176_846_000, 11600)
			.saturating_add(RocksDbWeight::get().reads(20_u64))
			.saturating_add(RocksDbWeight::get().writes(9_u64))
	}
	/// Storage: `Listings::DueQueue` (r:1 w:0)
	/// Proof: `Listings::DueQueue` (`max_values`: None, `max_size`: Some(2830), added: 5305, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueOverflow` (r:1 w:0)
	/// Proof: `Listings::DueOverflow` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn skip_empty_bucket() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `6295`
		// Minimum execution time: 5_097_000 picoseconds.
		Weight::from_parts(5_498_000, 6295)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	/// Storage: `Listings::DueQueue` (r:4 w:3)
	/// Proof: `Listings::DueQueue` (`max_values`: None, `max_size`: Some(2830), added: 5305, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueOverflow` (r:2 w:2)
	/// Proof: `Listings::DueOverflow` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Collection` (r:1 w:0)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:3)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:2 w:0)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:2 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Payment` (r:1 w:0)
	/// Proof: `Orders::Payment` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	fn process_due_overflow() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9857`
		//  Estimated: `22210`
		// Minimum execution time: 165_399_000 picoseconds.
		Weight::from_parts(172_709_000, 22210)
			.saturating_add(RocksDbWeight::get().reads(19_u64))
			.saturating_add(RocksDbWeight::get().writes(11_u64))
	}
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Listings::PausedTicks` (r:1 w:0)
	/// Proof: `Listings::PausedTicks` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Listings::LastPause` (r:1 w:0)
	/// Proof: `Listings::LastPause` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Listings::PauseStartedAt` (r:1 w:0)
	/// Proof: `Listings::PauseStartedAt` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn settle_subscription() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `346`
		//  Estimated: `3676`
		// Minimum execution time: 20_078_000 picoseconds.
		Weight::from_parts(21_379_000, 3676)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
