// This file is part of FRAME Contrib.

// Copyright (C) Virto Network.
// SPDX-License-Identifier: GPL-3.0-only

//! Autogenerated weights for `fc_pallet_listings`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 60.0.0
//! DATE: 2026-09-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `virto-bench-rknm6ml8jp2i`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=/home/runner/actions-runner/_work/_temp/runtime/fc_kitchensink_runtime.compact.compressed.wasm
// --pallet=fc_pallet_listings
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template=/home/runner/actions-runner/_work/frame-contrib/frame-contrib/pr/.maintain/frame-weight-template.hbs
// --header=/home/runner/actions-runner/_work/frame-contrib/frame-contrib/pr/.maintain/file_header.txt
// --output=pallets/listings/src/weights.rs
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `fc_pallet_listings`.
pub trait WeightInfo {
	fn create_inventory() -> Weight;
	fn archive_inventory() -> Weight;
	fn publish_item(q: u32, ) -> Weight;
	fn mark_item_can_transfer() -> Weight;
	fn mark_item_not_for_resale() -> Weight;
	fn set_item_price() -> Weight;
	fn clear_item_price() -> Weight;
	fn set_item_attribute(p: u32, q: u32, ) -> Weight;
	fn clear_item_attribute(p: u32, q: u32, ) -> Weight;
}

/// Weights for `fc_pallet_listings`, generated with the FRAME Contrib kitchensink runtime on reference hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionRoleOf` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionRoleOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionConfigOf` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionAccount` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionAccount` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn create_inventory() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `182`
		//  Estimated: `3593`
		// Minimum execution time: 32_350_000 picoseconds.
		Weight::from_parts(34_630_000, 3593)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:1 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	fn archive_inventory() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `258`
		//  Estimated: `3948`
		// Minimum execution time: 28_420_000 picoseconds.
		Weight::from_parts(30_660_000, 3948)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:2)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:1)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionConfigOf` (r:1 w:0)
	/// Proof: `ListingsCatalog::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::ItemConfigOf` (r:1 w:1)
	/// Proof: `ListingsCatalog::ItemConfigOf` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Account` (r:0 w:1)
	/// Proof: `ListingsCatalog::Account` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// The range of component `q` is `[1, 230]`.
	fn publish_item(q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `493`
		//  Estimated: `9864`
		// Minimum execution time: 82_470_000 picoseconds.
		Weight::from_parts(87_290_321, 9864)
			// Standard Error: 276
			.saturating_add(Weight::from_parts(2_363, 0).saturating_mul(q.into()))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:2 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	fn mark_item_can_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `559`
		//  Estimated: `6906`
		// Minimum execution time: 38_330_000 picoseconds.
		Weight::from_parts(41_130_000, 6906)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	fn mark_item_not_for_resale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `568`
		//  Estimated: `9864`
		// Minimum execution time: 43_209_000 picoseconds.
		Weight::from_parts(45_970_000, 9864)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:2 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	fn set_item_price() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `568`
		//  Estimated: `6906`
		// Minimum execution time: 48_599_000 picoseconds.
		Weight::from_parts(51_429_000, 6906)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:2 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	fn clear_item_price() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `590`
		//  Estimated: `6906`
		// Minimum execution time: 48_610_000 picoseconds.
		Weight::from_parts(51_580_000, 6906)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 59]`.
	/// The range of component `q` is `[1, 251]`.
	fn set_item_attribute(p: u32, q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `568`
		//  Estimated: `9864`
		// Minimum execution time: 42_100_000 picoseconds.
		Weight::from_parts(44_574_201, 9864)
			// Standard Error: 576
			.saturating_add(Weight::from_parts(15_657, 0).saturating_mul(p.into()))
			// Standard Error: 134
			.saturating_add(Weight::from_parts(1_568, 0).saturating_mul(q.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 59]`.
	/// The range of component `q` is `[1, 251]`.
	fn clear_item_attribute(p: u32, q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `614 + p * (1 ±0) + q * (1 ±0)`
		//  Estimated: `9864`
		// Minimum execution time: 37_670_000 picoseconds.
		Weight::from_parts(40_069_224, 9864)
			// Standard Error: 385
			.saturating_add(Weight::from_parts(17_591, 0).saturating_mul(p.into()))
			// Standard Error: 90
			.saturating_add(Weight::from_parts(663, 0).saturating_mul(q.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionRoleOf` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionRoleOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionConfigOf` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionAccount` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionAccount` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn create_inventory() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `182`
		//  Estimated: `3593`
		// Minimum execution time: 32_350_000 picoseconds.
		Weight::from_parts(34_630_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:1 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	fn archive_inventory() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `258`
		//  Estimated: `3948`
		// Minimum execution time: 28_420_000 picoseconds.
		Weight::from_parts(30_660_000, 3948)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:2)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:1)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionConfigOf` (r:1 w:0)
	/// Proof: `ListingsCatalog::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::ItemConfigOf` (r:1 w:1)
	/// Proof: `ListingsCatalog::ItemConfigOf` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Account` (r:0 w:1)
	/// Proof: `ListingsCatalog::Account` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// The range of component `q` is `[1, 230]`.
	fn publish_item(q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `493`
		//  Estimated: `9864`
		// Minimum execution time: 82_470_000 picoseconds.
		Weight::from_parts(87_290_321, 9864)
			// Standard Error: 276
			.saturating_add(Weight::from_parts(2_363, 0).saturating_mul(q.into()))
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:2 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	fn mark_item_can_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `559`
		//  Estimated: `6906`
		// Minimum execution time: 38_330_000 picoseconds.
		Weight::from_parts(41_130_000, 6906)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	fn mark_item_not_for_resale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `568`
		//  Estimated: `9864`
		// Minimum execution time: 43_209_000 picoseconds.
		Weight::from_parts(45_970_000, 9864)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:2 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	fn set_item_price() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `568`
		//  Estimated: `6906`
		// Minimum execution time: 48_599_000 picoseconds.
		Weight::from_parts(51_429_000, 6906)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:2 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	fn clear_item_price() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `590`
		//  Estimated: `6906`
		// Minimum execution time: 48_610_000 picoseconds.
		Weight::from_parts(51_580_000, 6906)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 59]`.
	/// The range of component `q` is `[1, 251]`.
	fn set_item_attribute(p: u32, q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `568`
		//  Estimated: `9864`
		// Minimum execution time: 42_100_000 picoseconds.
		Weight::from_parts(44_574_201, 9864)
			// Standard Error: 576
			.saturating_add(Weight::from_parts(15_657, 0).saturating_mul(p.into()))
			// Standard Error: 134
			.saturating_add(Weight::from_parts(1_568, 0).saturating_mul(q.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:1)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 59]`.
	/// The range of component `q` is `[1, 251]`.
	fn clear_item_attribute(p: u32, q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `614 + p * (1 ±0) + q * (1 ±0)`
		//  Estimated: `9864`
		// Minimum execution time: 37_670_000 picoseconds.
		Weight::from_parts(40_069_224, 9864)
			// Standard Error: 385
			.saturating_add(Weight::from_parts(17_591, 0).saturating_mul(p.into()))
			// Standard Error: 90
			.saturating_add(Weight::from_parts(663, 0).saturating_mul(q.into()))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
