// This file is part of FRAME Contrib.

// Copyright (C) Virto Network.
// SPDX-License-Identifier: GPL-3.0-only

//! Autogenerated weights for `fc_pallet_orders`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 60.0.0
//! DATE: 2026-09-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `virto-bench-rknm6ml8jp2i`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=/home/runner/actions-runner/_work/_temp/runtime/fc_kitchensink_runtime.compact.compressed.wasm
// --pallet=fc_pallet_orders
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template=/home/runner/actions-runner/_work/frame-contrib/frame-contrib/pr/.maintain/frame-weight-template.hbs
// --header=/home/runner/actions-runner/_work/frame-contrib/frame-contrib/pr/.maintain/file_header.txt
// --output=pallets/orders/src/weights.rs
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `fc_pallet_orders`.
pub trait WeightInfo {
	fn create_cart(p: u32, q: u32, ) -> Weight;
	fn set_cart_items(q: u32, ) -> Weight;
	fn checkout() -> Weight;
	fn cancel() -> Weight;
	fn pay() -> Weight;
}

/// Weights for `fc_pallet_orders`, generated with the FRAME Contrib kitchensink runtime on reference hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Orders::Cart` (r:1 w:1)
	/// Proof: `Orders::Cart` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `Orders::NextOrderId` (r:1 w:1)
	/// Proof: `Orders::NextOrderId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:64 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:64 w:0)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Order` (r:0 w:1)
	/// Proof: `Orders::Order` (`max_values`: None, `max_size`: Some(5431), added: 7906, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 10]`.
	/// The range of component `q` is `[1, 64]`.
	fn create_cart(p: u32, q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `446 + q * (250 ±0)`
		//  Estimated: `3554 + q * (3340 ±0)`
		// Minimum execution time: 30_910_000 picoseconds.
		Weight::from_parts(24_958_047, 3554)
			// Standard Error: 148_368
			.saturating_add(Weight::from_parts(287_556, 0).saturating_mul(p.into()))
			// Standard Error: 22_355
			.saturating_add(Weight::from_parts(12_285_948, 0).saturating_mul(q.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(q.into())))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 3340).saturating_mul(q.into()))
	}
	/// Storage: `Orders::Order` (r:1 w:1)
	/// Proof: `Orders::Order` (`max_values`: None, `max_size`: Some(5431), added: 7906, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:64 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:64 w:0)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// The range of component `q` is `[1, 64]`.
	fn set_cart_items(q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `630 + q * (251 ±0)`
		//  Estimated: `8896 + q * (3340 ±0)`
		// Minimum execution time: 24_380_000 picoseconds.
		Weight::from_parts(14_653_201, 8896)
			// Standard Error: 14_179
			.saturating_add(Weight::from_parts(12_508_981, 0).saturating_mul(q.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(q.into())))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 3340).saturating_mul(q.into()))
	}
	/// Storage: `Orders::Order` (r:1 w:1)
	/// Proof: `Orders::Order` (`max_values`: None, `max_size`: Some(5431), added: 7906, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:64 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:128 w:64)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionConfigOf` (r:1 w:0)
	/// Proof: `ListingsCatalog::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::ItemConfigOf` (r:64 w:0)
	/// Proof: `ListingsCatalog::ItemConfigOf` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Cart` (r:1 w:1)
	/// Proof: `Orders::Cart` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(107022), added: 109497, mode: `MaxEncodedLen`)
	fn checkout() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `21996`
		//  Estimated: `379614`
		// Minimum execution time: 2_757_796_000 picoseconds.
		Weight::from_parts(2_847_947_000, 379614)
			.saturating_add(T::DbWeight::get().reads(262_u64))
			.saturating_add(T::DbWeight::get().writes(69_u64))
	}
	/// Storage: `Orders::Order` (r:1 w:1)
	/// Proof: `Orders::Order` (`max_values`: None, `max_size`: Some(5431), added: 7906, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:64 w:64)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(107022), added: 109497, mode: `MaxEncodedLen`)
	fn cancel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `13547`
		//  Estimated: `190302`
		// Minimum execution time: 1_165_945_000 picoseconds.
		Weight::from_parts(1_205_894_000, 190302)
			.saturating_add(T::DbWeight::get().reads(68_u64))
			.saturating_add(T::DbWeight::get().writes(68_u64))
	}
	/// Storage: `Orders::Order` (r:1 w:1)
	/// Proof: `Orders::Order` (`max_values`: None, `max_size`: Some(5431), added: 7906, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:64 w:64)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:128 w:64)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Storage: `Payments::Payment` (r:64 w:64)
	/// Proof: `Payments::Payment` (`max_values`: None, `max_size`: Some(5035), added: 7510, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:2 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:1 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:2 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(159), added: 2634, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionConfigOf` (r:1 w:0)
	/// Proof: `ListingsCatalog::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::ItemConfigOf` (r:64 w:0)
	/// Proof: `ListingsCatalog::ItemConfigOf` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(107022), added: 109497, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Payment` (r:0 w:64)
	/// Proof: `Orders::Payment` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Account` (r:0 w:128)
	/// Proof: `ListingsCatalog::Account` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::ItemPriceOf` (r:0 w:64)
	/// Proof: `ListingsCatalog::ItemPriceOf` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::PendingSwapOf` (r:0 w:64)
	/// Proof: `ListingsCatalog::PendingSwapOf` (`max_values`: None, `max_size`: Some(79), added: 2554, mode: `MaxEncodedLen`)
	/// Storage: `Payments::PaymentParties` (r:0 w:64)
	/// Proof: `Payments::PaymentParties` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn pay() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `27330`
		//  Estimated: `481630`
		// Minimum execution time: 9_056_780_000 picoseconds.
		Weight::from_parts(9_283_504_000, 481630)
			.saturating_add(T::DbWeight::get().reads(335_u64))
			.saturating_add(T::DbWeight::get().writes(585_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Orders::Cart` (r:1 w:1)
	/// Proof: `Orders::Cart` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `Orders::NextOrderId` (r:1 w:1)
	/// Proof: `Orders::NextOrderId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:64 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:64 w:0)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Order` (r:0 w:1)
	/// Proof: `Orders::Order` (`max_values`: None, `max_size`: Some(5431), added: 7906, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 10]`.
	/// The range of component `q` is `[1, 64]`.
	fn create_cart(p: u32, q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `446 + q * (250 ±0)`
		//  Estimated: `3554 + q * (3340 ±0)`
		// Minimum execution time: 30_910_000 picoseconds.
		Weight::from_parts(24_958_047, 3554)
			// Standard Error: 148_368
			.saturating_add(Weight::from_parts(287_556, 0).saturating_mul(p.into()))
			// Standard Error: 22_355
			.saturating_add(Weight::from_parts(12_285_948, 0).saturating_mul(q.into()))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(q.into())))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 3340).saturating_mul(q.into()))
	}
	/// Storage: `Orders::Order` (r:1 w:1)
	/// Proof: `Orders::Order` (`max_values`: None, `max_size`: Some(5431), added: 7906, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:64 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:64 w:0)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// The range of component `q` is `[1, 64]`.
	fn set_cart_items(q: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `630 + q * (251 ±0)`
		//  Estimated: `8896 + q * (3340 ±0)`
		// Minimum execution time: 24_380_000 picoseconds.
		Weight::from_parts(14_653_201, 8896)
			// Standard Error: 14_179
			.saturating_add(Weight::from_parts(12_508_981, 0).saturating_mul(q.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(q.into())))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 3340).saturating_mul(q.into()))
	}
	/// Storage: `Orders::Order` (r:1 w:1)
	/// Proof: `Orders::Order` (`max_values`: None, `max_size`: Some(5431), added: 7906, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:64 w:0)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:128 w:64)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionConfigOf` (r:1 w:0)
	/// Proof: `ListingsCatalog::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::ItemConfigOf` (r:64 w:0)
	/// Proof: `ListingsCatalog::ItemConfigOf` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Cart` (r:1 w:1)
	/// Proof: `Orders::Cart` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(107022), added: 109497, mode: `MaxEncodedLen`)
	fn checkout() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `21996`
		//  Estimated: `379614`
		// Minimum execution time: 2_757_796_000 picoseconds.
		Weight::from_parts(2_847_947_000, 379614)
			.saturating_add(RocksDbWeight::get().reads(262_u64))
			.saturating_add(RocksDbWeight::get().writes(69_u64))
	}
	/// Storage: `Orders::Order` (r:1 w:1)
	/// Proof: `Orders::Order` (`max_values`: None, `max_size`: Some(5431), added: 7906, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:64 w:64)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(107022), added: 109497, mode: `MaxEncodedLen`)
	fn cancel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `13547`
		//  Estimated: `190302`
		// Minimum execution time: 1_165_945_000 picoseconds.
		Weight::from_parts(1_205_894_000, 190302)
			.saturating_add(RocksDbWeight::get().reads(68_u64))
			.saturating_add(RocksDbWeight::get().writes(68_u64))
	}
	/// Storage: `Orders::Order` (r:1 w:1)
	/// Proof: `Orders::Order` (`max_values`: None, `max_size`: Some(5431), added: 7906, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:64 w:64)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:128 w:64)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Storage: `Payments::Payment` (r:64 w:64)
	/// Proof: `Payments::Payment` (`max_values`: None, `max_size`: Some(5035), added: 7510, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:2 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:1 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:2 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(159), added: 2634, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionConfigOf` (r:1 w:0)
	/// Proof: `ListingsCatalog::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::ItemConfigOf` (r:64 w:0)
	/// Proof: `ListingsCatalog::ItemConfigOf` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(107022), added: 109497, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Payment` (r:0 w:64)
	/// Proof: `Orders::Payment` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Account` (r:0 w:128)
	/// Proof: `ListingsCatalog::Account` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::ItemPriceOf` (r:0 w:64)
	/// Proof: `ListingsCatalog::ItemPriceOf` (`max_values`: None, `max_size`: Some(93), added: 2568, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::PendingSwapOf` (r:0 w:64)
	/// Proof: `ListingsCatalog::PendingSwapOf` (`max_values`: None, `max_size`: Some(79), added: 2554, mode: `MaxEncodedLen`)
	/// Storage: `Payments::PaymentParties` (r:0 w:64)
	/// Proof: `Payments::PaymentParties` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn pay() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `27330`
		//  Estimated: `481630`
		// Minimum execution time: 9_056_780_000 picoseconds.
		Weight::from_parts(9_283_504_000, 481630)
			.saturating_add(RocksDbWeight::get().reads(335_u64))
			.saturating_add(RocksDbWeight::get().writes(585_u64))
	}
}
