// This file is part of FRAME Contrib.

// Copyright (C) Virto Network.
// SPDX-License-Identifier: GPL-3.0-only

//! Autogenerated weights for `fc_pallet_usage_subscription`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 60.0.0
//! DATE: 2026-10-02, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `virto-bench-soegbx1mb2x8`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=/home/runner/actions-runner/_work/_temp/runtime/fc_kitchensink_runtime.compact.compressed.wasm
// --pallet=fc_pallet_usage_subscription
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template=/home/runner/actions-runner/_work/frame-contrib/frame-contrib/pr/.maintain/frame-weight-template.hbs
// --header=/home/runner/actions-runner/_work/frame-contrib/frame-contrib/pr/.maintain/file_header.txt
// --output=pallets/usage-subscription/src/weights.rs
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `fc_pallet_usage_subscription`.
pub trait WeightInfo {
	fn publish_offer() -> Weight;
	fn withdraw_offer() -> Weight;
	fn subscribe() -> Weight;
	fn cancel() -> Weight;
	fn switch_offer() -> Weight;
	fn terminate_contract() -> Weight;
	fn set_paying_group() -> Weight;
	fn amend_contract() -> Weight;
	fn cancel_switch() -> Weight;
	fn amend_offer() -> Weight;
	fn pool_path() -> Weight;
	fn fee_path_check() -> Weight;
	fn hook_replaced() -> Weight;
	fn hook_amendment_in_force() -> Weight;
}

/// Weights for `fc_pallet_usage_subscription`, generated with the FRAME Contrib kitchensink runtime on reference hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::NextOfferId` (r:1 w:1)
	/// Proof: `UsageSubscription::NextOfferId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:1)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::ItemConfigOf` (r:1 w:1)
	/// Proof: `ListingsCatalog::ItemConfigOf` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:2)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemConditions` (r:1 w:1)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionRoleOf` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionRoleOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionConfigOf` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Account` (r:0 w:1)
	/// Proof: `ListingsCatalog::Account` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionAccount` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionAccount` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Offers` (r:0 w:1)
	/// Proof: `UsageSubscription::Offers` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn publish_offer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `540`
		//  Estimated: `9864`
		// Minimum execution time: 100_191_000 picoseconds.
		Weight::from_parts(105_386_000, 9864)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(13_u64))
	}
	/// Storage: `UsageSubscription::Offers` (r:1 w:1)
	/// Proof: `UsageSubscription::Offers` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn withdraw_offer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `92`
		//  Estimated: `3509`
		// Minimum execution time: 8_762_000 picoseconds.
		Weight::from_parts(9_373_000, 3509)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Communities::Info` (r:1 w:0)
	/// Proof: `Communities::Info` (`max_values`: None, `max_size`: Some(19), added: 2494, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Offers` (r:2 w:0)
	/// Proof: `UsageSubscription::Offers` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Contracts` (r:1 w:1)
	/// Proof: `UsageSubscription::Contracts` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::GroupOfAccount` (r:1 w:1)
	/// Proof: `UsageSubscription::GroupOfAccount` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::TrialUsed` (r:1 w:1)
	/// Proof: `UsageSubscription::TrialUsed` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Collection` (r:1 w:0)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:1 w:0)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemConditions` (r:2 w:0)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:2 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:0)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:1 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Payment` (r:1 w:0)
	/// Proof: `Orders::Payment` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:1)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueQueue` (r:1 w:1)
	/// Proof: `Listings::DueQueue` (`max_values`: None, `max_size`: Some(2830), added: 5305, mode: `MaxEncodedLen`)
	fn subscribe() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1406`
		//  Estimated: `6362`
		// Minimum execution time: 138_774_000 picoseconds.
		Weight::from_parts(144_502_000, 6362)
			.saturating_add(T::DbWeight::get().reads(23_u64))
			.saturating_add(T::DbWeight::get().writes(11_u64))
	}
	/// Storage: `Communities::Info` (r:1 w:0)
	/// Proof: `Communities::Info` (`max_values`: None, `max_size`: Some(19), added: 2494, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Contracts` (r:1 w:0)
	/// Proof: `UsageSubscription::Contracts` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn cancel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `580`
		//  Estimated: `3676`
		// Minimum execution time: 31_424_000 picoseconds.
		Weight::from_parts(33_257_000, 3676)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Communities::Info` (r:1 w:0)
	/// Proof: `Communities::Info` (`max_values`: None, `max_size`: Some(19), added: 2494, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Contracts` (r:1 w:1)
	/// Proof: `UsageSubscription::Contracts` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:2 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Offers` (r:1 w:0)
	/// Proof: `UsageSubscription::Offers` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemConditions` (r:1 w:0)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn switch_offer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `720`
		//  Estimated: `6362`
		// Minimum execution time: 51_211_000 picoseconds.
		Weight::from_parts(53_666_000, 6362)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `UsageSubscription::Contracts` (r:1 w:1)
	/// Proof: `UsageSubscription::Contracts` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueQueue` (r:1 w:1)
	/// Proof: `Listings::DueQueue` (`max_values`: None, `max_size`: Some(2830), added: 5305, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::GroupOfAccount` (r:1 w:1)
	/// Proof: `UsageSubscription::GroupOfAccount` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn terminate_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `539`
		//  Estimated: `6295`
		// Minimum execution time: 28_680_000 picoseconds.
		Weight::from_parts(30_353_000, 6295)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `Memberships::Account` (r:1 w:0)
	/// Proof: `Memberships::Account` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::PayingGroup` (r:1 w:1)
	/// Proof: `UsageSubscription::PayingGroup` (`max_values`: None, `max_size`: Some(59), added: 2534, mode: `MaxEncodedLen`)
	fn set_paying_group() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `485`
		//  Estimated: `3555`
		// Minimum execution time: 13_659_000 picoseconds.
		Weight::from_parts(14_489_000, 3555)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `UsageSubscription::Contracts` (r:1 w:1)
	/// Proof: `UsageSubscription::Contracts` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::GroupOfAccount` (r:1 w:0)
	/// Proof: `UsageSubscription::GroupOfAccount` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn amend_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `857`
		//  Estimated: `3676`
		// Minimum execution time: 53_051_000 picoseconds.
		Weight::from_parts(55_373_000, 3676)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `Communities::Info` (r:1 w:0)
	/// Proof: `Communities::Info` (`max_values`: None, `max_size`: Some(19), added: 2494, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Contracts` (r:1 w:1)
	/// Proof: `UsageSubscription::Contracts` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::GroupOfAccount` (r:1 w:0)
	/// Proof: `UsageSubscription::GroupOfAccount` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn cancel_switch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `622`
		//  Estimated: `3676`
		// Minimum execution time: 34_206_000 picoseconds.
		Weight::from_parts(35_668_000, 3676)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `UsageSubscription::Offers` (r:1 w:1)
	/// Proof: `UsageSubscription::Offers` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemConditions` (r:1 w:1)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:1)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::OfferAmendment` (r:0 w:1)
	/// Proof: `UsageSubscription::OfferAmendment` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	fn amend_offer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `495`
		//  Estimated: `3675`
		// Minimum execution time: 25_414_000 picoseconds.
		Weight::from_parts(26_635_000, 3675)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `UsageSubscription::PayingGroup` (r:1 w:0)
	/// Proof: `UsageSubscription::PayingGroup` (`max_values`: None, `max_size`: Some(59), added: 2534, mode: `MaxEncodedLen`)
	/// Storage: `Memberships::Account` (r:7 w:0)
	/// Proof: `Memberships::Account` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `Communities::Info` (r:1 w:0)
	/// Proof: `Communities::Info` (`max_values`: None, `max_size`: Some(19), added: 2494, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Contracts` (r:1 w:1)
	/// Proof: `UsageSubscription::Contracts` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:1 w:0)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::OfferAmendment` (r:1 w:0)
	/// Proof: `UsageSubscription::OfferAmendment` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	fn pool_path() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1337`
		//  Estimated: `18945`
		// Minimum execution time: 79_399_000 picoseconds.
		Weight::from_parts(82_633_000, 18945)
			.saturating_add(T::DbWeight::get().reads(12_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `UsageSubscription::PayingGroup` (r:1 w:0)
	/// Proof: `UsageSubscription::PayingGroup` (`max_values`: None, `max_size`: Some(59), added: 2534, mode: `MaxEncodedLen`)
	/// Storage: `Memberships::Account` (r:7 w:0)
	/// Proof: `Memberships::Account` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `Communities::Info` (r:1 w:0)
	/// Proof: `Communities::Info` (`max_values`: None, `max_size`: Some(19), added: 2494, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Contracts` (r:1 w:0)
	/// Proof: `UsageSubscription::Contracts` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:1 w:0)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::OfferAmendment` (r:1 w:0)
	/// Proof: `UsageSubscription::OfferAmendment` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	fn fee_path_check() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1337`
		//  Estimated: `18945`
		// Minimum execution time: 46_344_000 picoseconds.
		Weight::from_parts(48_226_000, 18945)
			.saturating_add(T::DbWeight::get().reads(12_u64))
	}
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	// `allow_replacement` and `on_replaced`, a conversion into a custom offer.
	fn hook_replaced() -> Weight {
		Weight::from_parts(60_000_000, 15000)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	// `on_amendment_in_force` for a standard contract.
	fn hook_amendment_in_force() -> Weight {
		Weight::from_parts(40_000_000, 10000)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `ListingsCatalog::Collection` (r:1 w:1)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::NextOfferId` (r:1 w:1)
	/// Proof: `UsageSubscription::NextOfferId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Item` (r:1 w:1)
	/// Proof: `ListingsCatalog::Item` (`max_values`: None, `max_size`: Some(865), added: 3340, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::ItemConfigOf` (r:1 w:1)
	/// Proof: `ListingsCatalog::ItemConfigOf` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:3 w:2)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemConditions` (r:1 w:1)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionRoleOf` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionRoleOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionConfigOf` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionConfigOf` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Account` (r:0 w:1)
	/// Proof: `ListingsCatalog::Account` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::CollectionAccount` (r:0 w:1)
	/// Proof: `ListingsCatalog::CollectionAccount` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Offers` (r:0 w:1)
	/// Proof: `UsageSubscription::Offers` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn publish_offer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `540`
		//  Estimated: `9864`
		// Minimum execution time: 100_191_000 picoseconds.
		Weight::from_parts(105_386_000, 9864)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(13_u64))
	}
	/// Storage: `UsageSubscription::Offers` (r:1 w:1)
	/// Proof: `UsageSubscription::Offers` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	fn withdraw_offer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `92`
		//  Estimated: `3509`
		// Minimum execution time: 8_762_000 picoseconds.
		Weight::from_parts(9_373_000, 3509)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Communities::Info` (r:1 w:0)
	/// Proof: `Communities::Info` (`max_values`: None, `max_size`: Some(19), added: 2494, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Offers` (r:2 w:0)
	/// Proof: `UsageSubscription::Offers` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Contracts` (r:1 w:1)
	/// Proof: `UsageSubscription::Contracts` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::GroupOfAccount` (r:1 w:1)
	/// Proof: `UsageSubscription::GroupOfAccount` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::TrialUsed` (r:1 w:1)
	/// Proof: `UsageSubscription::TrialUsed` (`max_values`: None, `max_size`: Some(18), added: 2493, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Collection` (r:1 w:0)
	/// Proof: `ListingsCatalog::Collection` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ListingsCatalog::Attribute` (r:1 w:0)
	/// Proof: `ListingsCatalog::Attribute` (`max_values`: None, `max_size`: Some(483), added: 2958, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemConditions` (r:2 w:0)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:2 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0xbacf5f93fbbb2c2ad87da081c8dac87cb56fe87734a0e4d6c8683a214145ac43` (r:1 w:1)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:0)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:1 w:0)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Orders::Payment` (r:1 w:0)
	/// Proof: `Orders::Payment` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:1)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueQueue` (r:1 w:1)
	/// Proof: `Listings::DueQueue` (`max_values`: None, `max_size`: Some(2830), added: 5305, mode: `MaxEncodedLen`)
	fn subscribe() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1406`
		//  Estimated: `6362`
		// Minimum execution time: 138_774_000 picoseconds.
		Weight::from_parts(144_502_000, 6362)
			.saturating_add(RocksDbWeight::get().reads(23_u64))
			.saturating_add(RocksDbWeight::get().writes(11_u64))
	}
	/// Storage: `Communities::Info` (r:1 w:0)
	/// Proof: `Communities::Info` (`max_values`: None, `max_size`: Some(19), added: 2494, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Contracts` (r:1 w:0)
	/// Proof: `UsageSubscription::Contracts` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn cancel() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `580`
		//  Estimated: `3676`
		// Minimum execution time: 31_424_000 picoseconds.
		Weight::from_parts(33_257_000, 3676)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Communities::Info` (r:1 w:0)
	/// Proof: `Communities::Info` (`max_values`: None, `max_size`: Some(19), added: 2494, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Contracts` (r:1 w:1)
	/// Proof: `UsageSubscription::Contracts` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:2 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Offers` (r:1 w:0)
	/// Proof: `UsageSubscription::Offers` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemConditions` (r:1 w:0)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn switch_offer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `720`
		//  Estimated: `6362`
		// Minimum execution time: 51_211_000 picoseconds.
		Weight::from_parts(53_666_000, 6362)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `UsageSubscription::Contracts` (r:1 w:1)
	/// Proof: `UsageSubscription::Contracts` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueQueue` (r:1 w:1)
	/// Proof: `Listings::DueQueue` (`max_values`: None, `max_size`: Some(2830), added: 5305, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::GroupOfAccount` (r:1 w:1)
	/// Proof: `UsageSubscription::GroupOfAccount` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn terminate_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `539`
		//  Estimated: `6295`
		// Minimum execution time: 28_680_000 picoseconds.
		Weight::from_parts(30_353_000, 6295)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `Memberships::Account` (r:1 w:0)
	/// Proof: `Memberships::Account` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::PayingGroup` (r:1 w:1)
	/// Proof: `UsageSubscription::PayingGroup` (`max_values`: None, `max_size`: Some(59), added: 2534, mode: `MaxEncodedLen`)
	fn set_paying_group() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `485`
		//  Estimated: `3555`
		// Minimum execution time: 13_659_000 picoseconds.
		Weight::from_parts(14_489_000, 3555)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `UsageSubscription::Contracts` (r:1 w:1)
	/// Proof: `UsageSubscription::Contracts` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::GroupOfAccount` (r:1 w:0)
	/// Proof: `UsageSubscription::GroupOfAccount` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn amend_contract() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `857`
		//  Estimated: `3676`
		// Minimum execution time: 53_051_000 picoseconds.
		Weight::from_parts(55_373_000, 3676)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `Communities::Info` (r:1 w:0)
	/// Proof: `Communities::Info` (`max_values`: None, `max_size`: Some(19), added: 2494, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Contracts` (r:1 w:1)
	/// Proof: `UsageSubscription::Contracts` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:1 w:1)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:0)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `Listings::DueCursor` (r:1 w:0)
	/// Proof: `Listings::DueCursor` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::GroupOfAccount` (r:1 w:0)
	/// Proof: `UsageSubscription::GroupOfAccount` (`max_values`: None, `max_size`: Some(50), added: 2525, mode: `MaxEncodedLen`)
	fn cancel_switch() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `622`
		//  Estimated: `3676`
		// Minimum execution time: 34_206_000 picoseconds.
		Weight::from_parts(35_668_000, 3676)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `UsageSubscription::Offers` (r:1 w:1)
	/// Proof: `UsageSubscription::Offers` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemConditions` (r:1 w:1)
	/// Proof: `Listings::ItemConditions` (`max_values`: None, `max_size`: Some(99), added: 2574, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Listings::ItemAmendments` (r:1 w:1)
	/// Proof: `Listings::ItemAmendments` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::OfferAmendment` (r:0 w:1)
	/// Proof: `UsageSubscription::OfferAmendment` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	fn amend_offer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `495`
		//  Estimated: `3675`
		// Minimum execution time: 25_414_000 picoseconds.
		Weight::from_parts(26_635_000, 3675)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `UsageSubscription::PayingGroup` (r:1 w:0)
	/// Proof: `UsageSubscription::PayingGroup` (`max_values`: None, `max_size`: Some(59), added: 2534, mode: `MaxEncodedLen`)
	/// Storage: `Memberships::Account` (r:7 w:0)
	/// Proof: `Memberships::Account` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `Communities::Info` (r:1 w:0)
	/// Proof: `Communities::Info` (`max_values`: None, `max_size`: Some(19), added: 2494, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Contracts` (r:1 w:1)
	/// Proof: `UsageSubscription::Contracts` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:1 w:0)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::OfferAmendment` (r:1 w:0)
	/// Proof: `UsageSubscription::OfferAmendment` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	fn pool_path() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1337`
		//  Estimated: `18945`
		// Minimum execution time: 79_399_000 picoseconds.
		Weight::from_parts(82_633_000, 18945)
			.saturating_add(RocksDbWeight::get().reads(12_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `UsageSubscription::PayingGroup` (r:1 w:0)
	/// Proof: `UsageSubscription::PayingGroup` (`max_values`: None, `max_size`: Some(59), added: 2534, mode: `MaxEncodedLen`)
	/// Storage: `Memberships::Account` (r:7 w:0)
	/// Proof: `Memberships::Account` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `Communities::Info` (r:1 w:0)
	/// Proof: `Communities::Info` (`max_values`: None, `max_size`: Some(19), added: 2494, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::Contracts` (r:1 w:0)
	/// Proof: `UsageSubscription::Contracts` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `Listings::Subscriptions` (r:1 w:0)
	/// Proof: `Listings::Subscriptions` (`max_values`: None, `max_size`: Some(211), added: 2686, mode: `MaxEncodedLen`)
	/// Storage: `UsageSubscription::OfferAmendment` (r:1 w:0)
	/// Proof: `UsageSubscription::OfferAmendment` (`max_values`: None, `max_size`: Some(86), added: 2561, mode: `MaxEncodedLen`)
	fn fee_path_check() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1337`
		//  Estimated: `18945`
		// Minimum execution time: 46_344_000 picoseconds.
		Weight::from_parts(48_226_000, 18945)
			.saturating_add(RocksDbWeight::get().reads(12_u64))
	}
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	// `allow_replacement` and `on_replaced`, a conversion into a custom offer.
	fn hook_replaced() -> Weight {
		Weight::from_parts(60_000_000, 15000)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	// `on_amendment_in_force` for a standard contract.
	fn hook_amendment_in_force() -> Weight {
		Weight::from_parts(40_000_000, 10000)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
