// This file is part of FRAME Contrib.

// Copyright (C) Virto Network.
// SPDX-License-Identifier: GPL-3.0-only

//! Weights for `fc_pallet_usage_subscription`
//!
//! Placeholders, until the benchmarks run on reference hardware (`/cmd bench`). Each value is a
//! conservative estimate of the call's work, including the listings subscription calls it makes.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `fc_pallet_usage_subscription`.
pub trait WeightInfo {
	fn publish_offer() -> Weight;
	fn withdraw_offer() -> Weight;
	fn subscribe() -> Weight;
	fn cancel() -> Weight;
	fn switch_offer() -> Weight;
	fn terminate_contract() -> Weight;
	fn cancel_switch() -> Weight;
}

/// Weights for `fc_pallet_usage_subscription`, to be generated with the FRAME Contrib kitchensink runtime on reference hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	fn publish_offer() -> Weight {
		Weight::from_parts(150_000_000, 30000)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(10_u64))
	}
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	fn withdraw_offer() -> Weight {
		Weight::from_parts(30_000_000, 5000)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	fn subscribe() -> Weight {
		Weight::from_parts(400_000_000, 60000)
			.saturating_add(T::DbWeight::get().reads(24_u64))
			.saturating_add(T::DbWeight::get().writes(16_u64))
	}
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	fn cancel() -> Weight {
		Weight::from_parts(150_000_000, 35000)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	fn switch_offer() -> Weight {
		Weight::from_parts(170_000_000, 35000)
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	fn terminate_contract() -> Weight {
		Weight::from_parts(130_000_000, 35000)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	fn cancel_switch() -> Weight {
		Weight::from_parts(150_000_000, 35000)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	fn publish_offer() -> Weight {
		Weight::from_parts(150_000_000, 30000)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(10_u64))
	}
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	fn withdraw_offer() -> Weight {
		Weight::from_parts(30_000_000, 5000)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	fn subscribe() -> Weight {
		Weight::from_parts(400_000_000, 60000)
			.saturating_add(RocksDbWeight::get().reads(24_u64))
			.saturating_add(RocksDbWeight::get().writes(16_u64))
	}
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	fn cancel() -> Weight {
		Weight::from_parts(150_000_000, 35000)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	fn switch_offer() -> Weight {
		Weight::from_parts(170_000_000, 35000)
			.saturating_add(RocksDbWeight::get().reads(13_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	fn terminate_contract() -> Weight {
		Weight::from_parts(130_000_000, 35000)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	fn cancel_switch() -> Weight {
		Weight::from_parts(150_000_000, 35000)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
}
