[package]
authors.workspace = true
description = "Traits for authenticating devices and credentials (WebAuthn, passkeys) in FRAME pallets."
edition.workspace = true
license.workspace = true
name = "fc-traits-authn"
repository.workspace = true
version.workspace = true

[dependencies]
codec.workspace = true
frame-support = { workspace = true, optional = true }
fc-traits-authn-proc.workspace = true
log.workspace = true
scale-info.workspace = true

[dev-dependencies]
sp-io = { workspace = true, features = ["std"] }

[features]
default = ["std", "runtime"]
runtime-benchmarks = ["runtime", "frame-support?/runtime-benchmarks"]
runtime = ["dep:frame-support"]
std = ["codec/std", "frame-support?/std", "log/std", "scale-info/std", "sp-io/std"]
