// This file is part of FRAME Contrib.

// Copyright (C) Virto Network.
// SPDX-License-Identifier: GPL-3.0-only

//! Autogenerated weights for `fc_pallet_pass`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 60.0.0
//! DATE: 2026-09-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `virto-bench-fynl6etprujf`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=/home/runner/actions-runner/_work/_temp/runtime/fc_kitchensink_runtime.compact.compressed.wasm
// --pallet=fc_pallet_pass
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template=/home/runner/actions-runner/_work/frame-contrib/frame-contrib/pr/.maintain/frame-weight-template.hbs
// --header=/home/runner/actions-runner/_work/frame-contrib/frame-contrib/pr/.maintain/file_header.txt
// --output=pallets/pass/src/weights.rs
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `fc_pallet_pass`.
pub trait WeightInfo {
	fn register() -> Weight;
	fn authenticate() -> Weight;
	fn authenticate_none() -> Weight;
	fn add_device() -> Weight;
	fn remove_device() -> Weight;
	fn add_session_key() -> Weight;
	fn remove_session_key() -> Weight;
}

/// Weights for `fc_pallet_pass`, generated with the FRAME Contrib kitchensink runtime on reference hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Pass::RegistrarConsiderations` (r:1 w:1)
	/// Proof: `Pass::RegistrarConsiderations` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
	/// Storage: `Pass::DeviceIds` (r:1 w:1)
	/// Proof: `Pass::DeviceIds` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Pass::DeviceConsiderations` (r:1 w:1)
	/// Proof: `Pass::DeviceConsiderations` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Pass::Devices` (r:0 w:1)
	/// Proof: `Pass::Devices` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	fn register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `250`
		//  Estimated: `6196`
		// Minimum execution time: 79_685_000 picoseconds.
		Weight::from_parts(83_501_000, 6196)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `Pass::Devices` (r:2 w:1)
	/// Proof: `Pass::Devices` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	fn authenticate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `313`
		//  Estimated: `6200`
		// Minimum execution time: 9_373_000 picoseconds.
		Weight::from_parts(10_053_000, 6200)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Pass::SessionKeys` (r:1 w:0)
	/// Proof: `Pass::SessionKeys` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn authenticate_none() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `300`
		//  Estimated: `3549`
		// Minimum execution time: 5_076_000 picoseconds.
		Weight::from_parts(5_587_000, 3549)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `Pass::Devices` (r:1 w:1)
	/// Proof: `Pass::Devices` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `Pass::DeviceIds` (r:1 w:1)
	/// Proof: `Pass::DeviceIds` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Pass::DeviceConsiderations` (r:1 w:1)
	/// Proof: `Pass::DeviceConsiderations` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
	fn add_device() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `569`
		//  Estimated: `3604`
		// Minimum execution time: 50_610_000 picoseconds.
		Weight::from_parts(53_523_000, 3604)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Pass::Devices` (r:2 w:1)
	/// Proof: `Pass::Devices` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `Pass::DeviceConsiderations` (r:1 w:1)
	/// Proof: `Pass::DeviceConsiderations` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
	/// Storage: `Pass::DeviceIds` (r:0 w:1)
	/// Proof: `Pass::DeviceIds` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn remove_device() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `627`
		//  Estimated: `6200`
		// Minimum execution time: 45_262_000 picoseconds.
		Weight::from_parts(48_156_000, 6200)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `Pass::Devices` (r:1 w:0)
	/// Proof: `Pass::Devices` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Pass::SessionKeys` (r:1 w:1)
	/// Proof: `Pass::SessionKeys` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:2 w:2)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(107022), added: 109497, mode: `MaxEncodedLen`)
	/// Storage: `Pass::CounterForSessionKeys` (r:1 w:1)
	/// Proof: `Pass::CounterForSessionKeys` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Pass::AccountSessionsCount` (r:1 w:1)
	/// Proof: `Pass::AccountSessionsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn add_session_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `703`
		//  Estimated: `219984`
		// Minimum execution time: 48_026_000 picoseconds.
		Weight::from_parts(50_490_000, 219984)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(107022), added: 109497, mode: `MaxEncodedLen`)
	/// Storage: `Pass::SessionKeys` (r:1 w:1)
	/// Proof: `Pass::SessionKeys` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Pass::CounterForSessionKeys` (r:1 w:1)
	/// Proof: `Pass::CounterForSessionKeys` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Pass::AccountSessionsCount` (r:1 w:1)
	/// Proof: `Pass::AccountSessionsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn remove_session_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `588`
		//  Estimated: `110487`
		// Minimum execution time: 26_025_000 picoseconds.
		Weight::from_parts(27_879_000, 110487)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Pass::RegistrarConsiderations` (r:1 w:1)
	/// Proof: `Pass::RegistrarConsiderations` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
	/// Storage: `Pass::DeviceIds` (r:1 w:1)
	/// Proof: `Pass::DeviceIds` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Pass::DeviceConsiderations` (r:1 w:1)
	/// Proof: `Pass::DeviceConsiderations` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Pass::Devices` (r:0 w:1)
	/// Proof: `Pass::Devices` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	fn register() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `250`
		//  Estimated: `6196`
		// Minimum execution time: 79_685_000 picoseconds.
		Weight::from_parts(83_501_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `Pass::Devices` (r:2 w:1)
	/// Proof: `Pass::Devices` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	fn authenticate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `313`
		//  Estimated: `6200`
		// Minimum execution time: 9_373_000 picoseconds.
		Weight::from_parts(10_053_000, 6200)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Pass::SessionKeys` (r:1 w:0)
	/// Proof: `Pass::SessionKeys` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn authenticate_none() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `300`
		//  Estimated: `3549`
		// Minimum execution time: 5_076_000 picoseconds.
		Weight::from_parts(5_587_000, 3549)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `Pass::Devices` (r:1 w:1)
	/// Proof: `Pass::Devices` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `Pass::DeviceIds` (r:1 w:1)
	/// Proof: `Pass::DeviceIds` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Pass::DeviceConsiderations` (r:1 w:1)
	/// Proof: `Pass::DeviceConsiderations` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
	fn add_device() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `569`
		//  Estimated: `3604`
		// Minimum execution time: 50_610_000 picoseconds.
		Weight::from_parts(53_523_000, 3604)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Pass::Devices` (r:2 w:1)
	/// Proof: `Pass::Devices` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `Pass::DeviceConsiderations` (r:1 w:1)
	/// Proof: `Pass::DeviceConsiderations` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(139), added: 2614, mode: `MaxEncodedLen`)
	/// Storage: `Pass::DeviceIds` (r:0 w:1)
	/// Proof: `Pass::DeviceIds` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn remove_device() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `627`
		//  Estimated: `6200`
		// Minimum execution time: 45_262_000 picoseconds.
		Weight::from_parts(48_156_000, 6200)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `Pass::Devices` (r:1 w:0)
	/// Proof: `Pass::Devices` (`max_values`: None, `max_size`: Some(130), added: 2605, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Pass::SessionKeys` (r:1 w:1)
	/// Proof: `Pass::SessionKeys` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:2 w:2)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(107022), added: 109497, mode: `MaxEncodedLen`)
	/// Storage: `Pass::CounterForSessionKeys` (r:1 w:1)
	/// Proof: `Pass::CounterForSessionKeys` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Pass::AccountSessionsCount` (r:1 w:1)
	/// Proof: `Pass::AccountSessionsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn add_session_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `703`
		//  Estimated: `219984`
		// Minimum execution time: 48_026_000 picoseconds.
		Weight::from_parts(50_490_000, 219984)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(107022), added: 109497, mode: `MaxEncodedLen`)
	/// Storage: `Pass::SessionKeys` (r:1 w:1)
	/// Proof: `Pass::SessionKeys` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Pass::CounterForSessionKeys` (r:1 w:1)
	/// Proof: `Pass::CounterForSessionKeys` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Pass::AccountSessionsCount` (r:1 w:1)
	/// Proof: `Pass::AccountSessionsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn remove_session_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `588`
		//  Estimated: `110487`
		// Minimum execution time: 26_025_000 picoseconds.
		Weight::from_parts(27_879_000, 110487)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
}
