// This file is part of FRAME Contrib.

// Copyright (C) Virto Network.
// SPDX-License-Identifier: GPL-3.0-only

//! Autogenerated weights for `fc_pallet_gas_transaction_payment`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 60.0.0
//! DATE: 2026-10-07, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `virto-bench-rj0jabyzl7sx`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=/home/runner/actions-runner/_work/_temp/runtime/fc_kitchensink_runtime.compact.compressed.wasm
// --pallet=fc_pallet_gas_transaction_payment
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template=/home/runner/actions-runner/_work/frame-contrib/frame-contrib/pr/.maintain/frame-weight-template.hbs
// --header=/home/runner/actions-runner/_work/frame-contrib/frame-contrib/pr/.maintain/file_header.txt
// --output=pallets/gas-transaction-payment/src/weights.rs
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame::weights_prelude::*;

/// Weight functions needed for `fc_pallet_gas_transaction_payment`.
pub trait WeightInfo {
	fn charge_transaction_payment() -> Weight;
}

/// Weights for `fc_pallet_gas_transaction_payment`, generated with the FRAME Contrib kitchensink runtime on reference hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Memberships::Account` (r:4 w:0)
	/// Proof: `Memberships::Account` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `Memberships::Attribute` (r:4 w:1)
	/// Proof: `Memberships::Attribute` (`max_values`: None, `max_size`: Some(481), added: 2956, mode: `MaxEncodedLen`)
	/// Storage: `Memberships::Collection` (r:1 w:1)
	/// Proof: `Memberships::Collection` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x1626a7cafeeb4e57fbac2a0be0eab1c08391ea53613e620bf32ff98c26095f8f` (r:0 w:1)
	/// Proof: UNKNOWN KEY `0x1626a7cafeeb4e57fbac2a0be0eab1c08391ea53613e620bf32ff98c26095f8f` (r:0 w:1)
	fn charge_transaction_payment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `670`
		//  Estimated: `12814`
		// Minimum execution time: 78_198_000 picoseconds.
		Weight::from_parts(81_574_000, 12814)
			.saturating_add(T::DbWeight::get().reads(9_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Memberships::Account` (r:4 w:0)
	/// Proof: `Memberships::Account` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `Memberships::Attribute` (r:4 w:1)
	/// Proof: `Memberships::Attribute` (`max_values`: None, `max_size`: Some(481), added: 2956, mode: `MaxEncodedLen`)
	/// Storage: `Memberships::Collection` (r:1 w:1)
	/// Proof: `Memberships::Collection` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
	/// Storage: UNKNOWN KEY `0x1626a7cafeeb4e57fbac2a0be0eab1c08391ea53613e620bf32ff98c26095f8f` (r:0 w:1)
	/// Proof: UNKNOWN KEY `0x1626a7cafeeb4e57fbac2a0be0eab1c08391ea53613e620bf32ff98c26095f8f` (r:0 w:1)
	fn charge_transaction_payment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `670`
		//  Estimated: `12814`
		// Minimum execution time: 78_198_000 picoseconds.
		Weight::from_parts(81_574_000, 12814)
			.saturating_add(RocksDbWeight::get().reads(9_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}
