// This file is part of FRAME Contrib.

// Copyright (C) Virto Network.
// SPDX-License-Identifier: GPL-3.0-only

//! Autogenerated weights for `fc_pallet_gas_transaction_payment`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 60.0.0
//! DATE: 2026-09-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `virto-bench-rknm6ml8jp2i`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=/home/runner/actions-runner/_work/_temp/runtime/fc_kitchensink_runtime.compact.compressed.wasm
// --pallet=fc_pallet_gas_transaction_payment
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template=/home/runner/actions-runner/_work/frame-contrib/frame-contrib/pr/.maintain/frame-weight-template.hbs
// --header=/home/runner/actions-runner/_work/frame-contrib/frame-contrib/pr/.maintain/file_header.txt
// --output=pallets/gas-transaction-payment/src/weights.rs
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame::weights_prelude::*;

/// Weight functions needed for `fc_pallet_gas_transaction_payment`.
pub trait WeightInfo {
	fn charge_transaction_payment() -> Weight;
}

/// Weights for `fc_pallet_gas_transaction_payment`, generated with the FRAME Contrib kitchensink runtime on reference hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	// Conservative estimate for the check, `prepare_gas` and `burn_gas` of a `NonFungibleGasTank`
	// scanning `DefaultMaxScan` (4) items twice (the check and `prepare_gas`), then burning from the
	// noted tank, with no scan; rounded up. The fee extension's weight is added separately, by
	// `ChargeTransactionPayment::weight`.
	/// Storage: `Memberships::Account` (r:8 w:0)
	/// Proof: `Memberships::Account` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `Memberships::Attribute` (r:10 w:1)
	/// Proof: `Memberships::Attribute` (`max_values`: None, `max_size`: Some(481), added: 2956, mode: `MaxEncodedLen`)
	/// Storage: `Memberships::Collection` (r:1 w:1)
	/// Proof: `Memberships::Collection` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
	/// Storage: `NonFungibleGasTank::PayingItem` (r:1 w:2)
	/// Proof: `NonFungibleGasTank::PayingItem` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn charge_transaction_payment() -> Weight {
		Weight::from_parts(250_000_000, 30_000)
			.saturating_add(T::DbWeight::get().reads(32_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	// PLACEHOLDER: regenerated by /cmd bench on the PR
	// Conservative estimate for the check, `prepare_gas` and `burn_gas` of a `NonFungibleGasTank`
	// scanning `DefaultMaxScan` (4) items twice (the check and `prepare_gas`), then burning from the
	// noted tank, with no scan; rounded up. The fee extension's weight is added separately, by
	// `ChargeTransactionPayment::weight`.
	/// Storage: `Memberships::Account` (r:8 w:0)
	/// Proof: `Memberships::Account` (`max_values`: None, `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `Memberships::Attribute` (r:10 w:1)
	/// Proof: `Memberships::Attribute` (`max_values`: None, `max_size`: Some(481), added: 2956, mode: `MaxEncodedLen`)
	/// Storage: `Memberships::Collection` (r:1 w:1)
	/// Proof: `Memberships::Collection` (`max_values`: None, `max_size`: Some(82), added: 2557, mode: `MaxEncodedLen`)
	/// Storage: `NonFungibleGasTank::PayingItem` (r:1 w:2)
	/// Proof: `NonFungibleGasTank::PayingItem` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn charge_transaction_payment() -> Weight {
		Weight::from_parts(250_000_000, 30_000)
			.saturating_add(RocksDbWeight::get().reads(32_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
}
