// This file is part of FRAME Contrib.

// Copyright (C) Virto Network.
// SPDX-License-Identifier: GPL-3.0-only

//! Autogenerated weights for `fc_pallet_black_hole`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 60.0.0
//! DATE: 2026-09-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `virto-bench-rknm6ml8jp2i`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=/home/runner/actions-runner/_work/_temp/runtime/fc_kitchensink_runtime.compact.compressed.wasm
// --pallet=fc_pallet_black_hole
// --extrinsic=*
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template=/home/runner/actions-runner/_work/frame-contrib/frame-contrib/pr/.maintain/frame-weight-template.hbs
// --header=/home/runner/actions-runner/_work/frame-contrib/frame-contrib/pr/.maintain/file_header.txt
// --output=pallets/black-hole/src/weights.rs
// --quiet

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame::weights_prelude::*;

/// Weight functions needed for `fc_pallet_black_hole`.
pub trait WeightInfo {
	fn burn() -> Weight;
	fn dispatch_as_event_horizon() -> Weight;
}

/// Weights for `fc_pallet_black_hole`, generated with the FRAME Contrib kitchensink runtime on reference hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `BlackHole::LastBurn` (r:1 w:1)
	/// Proof: `BlackHole::LastBurn` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `BlackHole::BlackHoleMass` (r:1 w:1)
	/// Proof: `BlackHole::BlackHoleMass` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `184`
		//  Estimated: `3593`
		// Minimum execution time: 33_521_000 picoseconds.
		Weight::from_parts(35_450_000, 3593)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn dispatch_as_event_horizon() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `89`
		//  Estimated: `3593`
		// Minimum execution time: 13_610_000 picoseconds.
		Weight::from_parts(15_210_000, 3593)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `BlackHole::LastBurn` (r:1 w:1)
	/// Proof: `BlackHole::LastBurn` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `BlackHole::BlackHoleMass` (r:1 w:1)
	/// Proof: `BlackHole::BlackHoleMass` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `184`
		//  Estimated: `3593`
		// Minimum execution time: 33_521_000 picoseconds.
		Weight::from_parts(35_450_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn dispatch_as_event_horizon() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `89`
		//  Estimated: `3593`
		// Minimum execution time: 13_610_000 picoseconds.
		Weight::from_parts(15_210_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
