// This file is part of Substrate.

// Copyright (C) Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


//! Autogenerated weights for `pallet_account_profile`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-02, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `akalabeth`, CPU: `AMD Ryzen 7 6800HS Creator Edition`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// /home/jbrown/.cargo/bin/frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/kreivo-runtime/kreivo_runtime.wasm
// --pallets
// pallet_account_profile
// --extrinsic
// 
// --steps
// 50
// --repeat
// 20
// --template
// frame-weight-template.hbs
// --output
// weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]
#![allow(dead_code)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_account_profile`.
pub trait WeightInfo {
	fn set_profile() -> Weight;
}

/// Weights for `pallet_account_profile` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Content::ItemState` (r:1 w:0)
	/// Proof: `Content::ItemState` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AccountProfile::Profiles` (r:0 w:1)
	/// Proof: `AccountProfile::Profiles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_profile() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `227`
		//  Estimated: `3692`
		// Minimum execution time: 16_811_000 picoseconds.
		Weight::from_parts(17_112_000, 3692)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Content::ItemState` (r:1 w:0)
	/// Proof: `Content::ItemState` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AccountProfile::Profiles` (r:0 w:1)
	/// Proof: `AccountProfile::Profiles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_profile() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `227`
		//  Estimated: `3692`
		// Minimum execution time: 16_811_000 picoseconds.
		Weight::from_parts(17_112_000, 3692)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
